language: node_js
sudo: required
node_js:
- '4.1'
env:
  - CXX=g++-4.8
addons:
ssh_known_hosts: stevenlyall.me
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
- set -x
- openssl aes-256-cbc -K $encrypted_7af3dc9fdb66_key -iv $encrypted_7af3dc9fdb66_iv
  -in eval-n-site-deploy-key.enc -out eval-n-site-deploy-key -d
- rm eval-n-site-deploy-key.enc
- chmod 600 eval-n-site-deploy-key
- mv eval-n-site-deploy-key ~/.ssh/id_rsa
script:
- deploy_scripts/deploy.sh
